name: embodied-policy
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - numpy
  - pyyaml
  - pytest
  - pip
  - pip:
      - mani_skill==3.0.1

